export const myNFTUnlicensedData = [
  {
    avatar: '/static/fake/detail.svg',
    name: 'My Little Piggie #4594',
    address: '0x4bd499091b197f85CafFcaF95a38d4c7A8f6A4A9',
    pool: 'My Little Piggie',
    value: '20',
  },
  {
    avatar: '/static/fake/detail.svg',
    name: 'Createra Genesis Land #8279',
    address: '0x4bd499091b197f85CafFcaF95a38d4c7A8f6A4A9',
    pool: 'Createra Genesis Land ',
    value: '20',
  },
  {
    avatar: '/static/fake/detail.svg',
    name: 'The Memes by 6529 #8279',
    address: '0x4bd499091b197f85CafFcaF95a38d4c7A8f6A4A9',
    pool: undefined,
    value: '20',
  },
  {
    avatar: '/static/fake/detail.svg',
    name: 'PEPELAND - Official #8279',
    address: '0x4bd499091b197f85CafFcaF95a38d4c7A8f6A4A9',
    pool: 'PEPELAND - Official ',
    value: '20',
  },
  {
    avatar: '/static/fake/detail.svg',
    name: 'Boots By Jeremy Booth #8279',
    address: '0x4bd499091b197f85CafFcaF95a38d4c7A8f6A4A9',
    pool: 'Boots By Jeremy Booth',
    value: '20',
  },
]

export const myNFTLicensedData = [
  {
    avatar: '/static/fake/detail.svg',
    name: 'My Little Piggie #4594',
    pool: 'My Little Piggie',
    currentHighestBid: '50 ETH',
    TotalRevenue: '0.01 ETH',
    lockStatus: undefined,
  },
  {
    avatar: '/static/fake/detail.svg',
    name: 'Createra Genesis Land #8279',
    pool: 'Createra Genesis Land ',
    currentHighestBid: '50 ETH',
    TotalRevenue: '0.01 ETH',
    lockStatus: undefined,
  },
  {
    avatar: '/static/fake/detail.svg',
    name: 'The Memes by 6529 #8279',
    pool: undefined,
    currentHighestBid: '50 ETH',
    TotalRevenue: '0.01 ETH',
    lockStatus: 'After 24 hours',
  },
  {
    avatar: '/static/fake/detail.svg',
    name: 'PEPELAND - Official #8279',
    pool: 'PEPELAND - Official ',
    currentHighestBid: '50 ETH',
    TotalRevenue: '0.01 ETH',
    lockStatus: 'After 1 month',
  },
  {
    avatar: '/static/fake/detail.svg',
    name: 'Boots By Jeremy Booth #8279',
    pool: 'Boots By Jeremy Booth',
    currentHighestBid: '50 ETH',
    TotalRevenue: '0.01 ETH',
    lockStatus: 'After 24 days',
  },
]

export const buyOrderLicensedData = [
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    currentHighestBid: '50 ETH',
    highestOffer: '0.54 ETH',
    duration: '-',
    balance: '0.54 ETH',
    status: 'Active',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    currentHighestBid: '50 ETH',
    highestOffer: '154 ETH',
    duration: '-',
    balance: '0.54 ETH',
    status: 'Active',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    currentHighestBid: '50 ETH',
    highestOffer: '54 ETH',
    duration: '1 Year',
    balance: '0.54 ETH',
    status: 'Active',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    currentHighestBid: '50 ETH',
    highestOffer: '4 ETH',
    duration: '-',
    balance: '0.54 ETH',
    status: 'Active',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    currentHighestBid: '50 ETH',
    highestOffer: '25 ETH',
    duration: '-',
    balance: '0.54 ETH',
    status: 'Active',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    currentHighestBid: '50 ETH',
    highestOffer: '0.54 ETH',
    duration: '-',
    balance: '0.54 ETH',
    status: 'Active',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    currentHighestBid: '50 ETH',
    highestOffer: '5 ETH',
    duration: '-',
    balance: '0.54 ETH',
    status: 'Active',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    currentHighestBid: '50 ETH',
    highestOffer: '0.54 ETH',
    duration: '-',
    balance: '0.54 ETH',
    status: 'Active',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    currentHighestBid: '50 ETH',
    highestOffer: '54 ETH',
    duration: '-',
    balance: '0.54 ETH',
    status: 'Active',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    currentHighestBid: '50 ETH',
    highestOffer: '3 ETH',
    duration: '1 Year',
    balance: '0.54 ETH',
    status: 'Jan 18,2023',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    currentHighestBid: '50 ETH',
    highestOffer: '54 ETH',
    duration: '-',
    balance: '0.54 ETH',
    status: 'Active',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    currentHighestBid: '50 ETH',
    highestOffer: '0.54 ETH',
    duration: '-',
    balance: '0.54 ETH',
    status: 'Active',
  },
]

export const buyOrderOfferMade = [
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    subScriptionFee: '54',
    currentLowestBid: '50 ETH',
    highestOffer: '0.54 ETH',
    myOffer: '0.54 ETH',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    subScriptionFee: '64',
    currentLowestBid: '50 ETH',
    highestOffer: '154 ETH',
    myOffer: '0.54 ETH',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    subScriptionFee: '24',
    currentLowestBid: '50 ETH',
    highestOffer: '54 ETH',
    myOffer: '0.54 ETH',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    subScriptionFee: '34',
    currentLowestBid: '50 ETH',
    highestOffer: '4 ETH',
    myOffer: '0.54 ETH',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    subScriptionFee: '14',
    currentLowestBid: '50 ETH',
    highestOffer: '25 ETH',
    myOffer: '0.54 ETH',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    subScriptionFee: '33',
    currentLowestBid: '50 ETH',
    highestOffer: '0.54 ETH',
    myOffer: '0.54 ETH',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    subScriptionFee: '54',
    currentLowestBid: '50 ETH',
    highestOffer: '5 ETH',
    myOffer: '0.54 ETH',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    subScriptionFee: '84',
    currentLowestBid: '50 ETH',
    highestOffer: '0.54 ETH',
    myOffer: '0.54 ETH',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    subScriptionFee: '54',
    currentLowestBid: '50 ETH',
    highestOffer: '54 ETH',
    myOffer: '0.54 ETH',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    subScriptionFee: '66',
    currentLowestBid: '50 ETH',
    highestOffer: '3 ETH',
    myOffer: '',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    subScriptionFee: '64',
    currentLowestBid: '50 ETH',
    highestOffer: '54 ETH',
    myOffer: '0.54 ETH',
  },
  {
    poolName: 'My Littele Piggie',
    nftInPool: '1,245',
    subScriptionFee: '54',
    currentLowestBid: '50 ETH',
    highestOffer: '0.54 ETH',
    myOffer: '0.54 ETH',
  },
]
